discovery_context:
  business:
    key_stakeholders:
      - Alice Acme, CEO
      - Bob Acme, CTO
      - Carol Acme, CFO
    pain_points:
      - Supply chain inefficiencies
      - Increasing operational costs
      - Market competition
    strategic_goals:
      - Increase market share
      - Improve operational efficiency
      - Adopt sustainable practices
    success_metrics:
      - Market Share
      - Revenue Growth
      - Operational Efficiency
  compliance:
    data_privacy:
      - GDPR
      - CCPA
    requirements:
      - robust data encryption
      - regular compliance audits
    security_controls:
      - MFA
      - Firewall
      - IDS
  data_sources:
    external:
      - name: "Google Cloud Storage"
        description: "Global marketing data lake"
        regions: ["us-central1", "europe-west1"]
        data_types: ["csv", "json"]
        size_estimate: "30TB"
      - name: "IBM Cloud Object Storage"
        description: "Legacy production backups"
        regions: ["us-south"]
        data_types: ["binary", "logs"]
        size_estimate: "15TB"
      - name: "Oracle Autonomous Database"
        description: "Customer transaction data"
        regions: ["us-east-2"]
        data_types: ["oracle"]
        size_estimate: "750GB"
    internal:
      - name: "Confluence"
        description: "Internal documentation portal"
        workspaces: ["Engineering", "Operations", "Finance"]
        access_level: "Enterprise"
      - name: "Microsoft Teams"
        description: "Collaboration and communication tool"
        channels: ["General", "Operations", "Support"]
        retention_policy: "180 days"
      - name: "Dropbox Business"
        description: "Shared corporate files"
        shared_drives: ["Executive", "HR", "Sales"]
        size_estimate: "3TB"
  it_estate:
    applications:
      - name: "Acme Portal"
        type: "Web Application"
        tech_stack: ["Angular", "Spring Boot", "MySQL"]
        hosting: "Google App Engine"
        status: "Production"
      - name: "Acme Mobile"
        type: "Native Mobile"
        tech_stack: ["Swift", "Kotlin"]
        platforms: ["iOS", "Android"]
        status: "Beta"
      - name: "Acme Dashboard"
        type: "Web Application"
        tech_stack: ["React", "Django"]
        hosting: "AWS Elastic Beanstalk"
        status: "Production"
    cloud_services:
      - name: "Google Cloud"
        services:
          - "App Engine"
          - "Cloud SQL"
          - "BigQuery"
        regions: ["us-central1", "asia-east1"]
      - name: "IBM Cloud"
        services:
          - "Cloud Foundry"
          - "Kubernetes Service"
        regions: ["us-south"]
      - name: "AWS"
        services:
          - "EC2"
          - "S3"
          - "Lambda"
        regions: ["us-east-2"]
    databases:
      - name: "Transaction Data"
        type: "MySQL"
        version: "8.0"
        hosting: "Google Cloud SQL"
        size: "1TB"
        backup_strategy: "Hourly backups"
      - name: "Analytics DB"
        type: "BigQuery"
        datasets: ["sales_data", "customer_engagement", "inventory"]
        size: "20TB"
      - name: "Session Cache"
        type: "Redis"
        version: "7.0"
        hosting: "AWS ElastiCache"
        purpose: "User session caching"
    integration_points:
      - name: "Payment Processor"
        type: "REST API"
        provider: "PayPal"
        endpoints: ["payments", "refunds", "subscriptions"]
      - name: "Notification Service"
        type: "SMTP/API"
        provider: "Mailgun"
        volume: "200k emails/month"
      - name: "User Authentication"
        type: "OAuth2/OIDC"
        provider: "Okta"
        integrations: ["Google", "Microsoft", "LinkedIn"]
documents:
  input_directory: ./data/input
  output_directory: ./data/output
  supported_formats:
    - .pdf
    - .docx
    - .txt
    - .md
organization:
  industry: "Manufacturing"
  location: "Los Angeles"
  name: "Acme Corp"
  size: "Large"
